# Use postgres/example user/password credentials
version: "3.1"

services:
  nemo-database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    ports:
      - 5432:5432
